### ISSUE TITLE
I don't know how to fix 1 problem in npm test, but I fixed other mentor comments

### ISSUE THREAD

**Issue by BogdanParubchenk01** [mate-academy/layout_catalog#2601]
I don't know hove to fix 1 problem in npm test, but I fixed other mentor comments
[DEMO LINK](https://BogdanParubchenk01.github.io/layout_catalog/)
[TEST REPORT LINK](https://BogdanParubchenk01.github.io/layout_catalog/report/html_report/)

_Originally posted by @BogdanParubchenk01 in https://github.com/mate-academy/layout_catalog/pull/2576#pullrequestreview-1264659642_

**Comment by Diego121985** [comment]
- [DEMO LINK](https://Diego121985.github.io/layout_catalog/)
- [TEST REPORT LINK](https://diegoleite59986@gmail.com.github.io/layout_catalog/report/html_report/)
